Repository beaugmented/agency, pull requests merged in 2024-10, with the labels that each got.

#302 data generation
  .vscode/settings.json
  packages/safegen/.varmint/openai-safegen/How many planets are in the solar system_-0.input.json
  packages/safegen/.varmint/openai-safegen/How many planets are in the solar system_-0.output.json
  packages/safegen/CHANGELOG.md
  packages/safegen/break-check.config.json
  packages/safegen/package.json
  packages/safegen/src/07.schema.json
  packages/safegen/src/index.ts
  packages/safegen/src/openai/build-open-ai-request-params.ts
  packages/safegen/src/openai/index.ts
  packages/safegen/src/openai/open-ai-safegen-cached.ts
  packages/safegen/src/openai/open-ai-safegen.ts
  packages/safegen/src/openai/set-up-open-ai-generator.ts
  packages/safegen/src/safegen.test.ts
  packages/safegen/src/safegen.ts
  packages/safegen/tsconfig.json
  packages/safegen/tsup.config.ts
  packages/safegen/vite-env.d.ts
  packages/safegen/vitest.config.ts
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement, tests, Review effort [1-5]: 3

#303 token budget
  .changeset/happy-ways-rest.md
  packages/safegen/.varmint/openai-safegen/How many planets are in the solar system_-0.input.json
  packages/safegen/.varmint/openai-safegen/How many planets are in the solar system_-0.output.json
  packages/safegen/src/openai/open-ai-safegen-cached.ts
  packages/safegen/src/openai/pricing-facts.ts
  packages/safegen/src/openai/set-up-open-ai-generator.ts
  packages/safegen/src/safegen.test.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#311 safegen logger
  .changeset/blue-ghosts-build.md
  .changeset/nine-keys-return.md
  packages/safegen/src/openai/open-ai-safegen-cached.ts
  packages/safegen/src/safegen.test.ts
Labels: enhancement, tests, Review effort [1-5]: 3

#318 update vscode recommendations
  .vscode/extensions.json
Labels: Review effort [1-5]: 1, configuration changes

#319 safegen cache mode
  .changeset/tender-peas-rest.md
  packages/safegen/src/openai/open-ai-safegen-cached.ts
  packages/safegen/src/safegen.test.ts
Labels: enhancement, tests, Review effort [1-5]: 2

#320 🔧 nvmrc -> node-version; + .bun-version
  .bun-version
  .github/workflows/integration.yml
  .github/workflows/release.yml
  .github/workflows/semver.yml
  .node-version
  package.json
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#322 node 22
  .node-version
  package.json
  packages/agency/package.json
  packages/safegen/package.json
  pnpm-lock.yaml
Labels: enhancement, Review effort [1-5]: 2, dependencies

#323 eslint.config.ts
  .vscode/settings.json
  eslint.config.ts
  eslint_.d.ts
  package.json
  packages/agency/package.json
  packages/safegen/package.json
  pnpm-lock.yaml
  tsconfig.json
Labels: enhancement, Review effort [1-5]: 3, configuration changes

#324 🔧 consolidate settings
  .vscode/settings.json
  package.json
Labels: enhancement, configuration changes, Review effort [1-5]: 2

#350 🚂 prioritization test
  packages/safegen/.varmint/openai-safegen/-items-for-me_-at-varying-levels-of-difficulty-and-importance.-0+cc482136fd0050c9a9b8719615a0c514c16bea75afd9984df9d4bcfe498b4286.input.json
  packages/safegen/.varmint/openai-safegen/-items-for-me_-at-varying-levels-of-difficulty-and-importance.-0+cc482136fd0050c9a9b8719615a0c514c16bea75afd9984df9d4bcfe498b4286.output.json
  packages/safegen/.varmint/openai-safegen/te-a-personal-blog-post___------_completed__-false_----__--___-0+9773beabf9df49792a05e93d4561ffbe725b0bffee120f9c49f21d85283a895f.input.json
  packages/safegen/.varmint/openai-safegen/te-a-personal-blog-post___------_completed__-false_----__--___-0+9773beabf9df49792a05e93d4561ffbe725b0bffee120f9c49f21d85283a895f.output.json
  packages/safegen/README.md
  packages/safegen/src/safegen.test.ts
  pnpm-lock.yaml
Labels: Review effort [1-5]: 3

#368 setup semver testing conditions
  .changeset/rare-shirts-lay.md
  packages/safegen/__tests__/public/safegen.test.ts
Labels: Review effort [1-5]: 2

#367 Only allow openai models we have pricing data for
  .changeset/twelve-apples-nail.md
  packages/safegen/break-check.config.json
  packages/safegen/package.json
  packages/safegen/src/openai/open-ai-safegen-cached.ts
  packages/safegen/src/openai/open-ai-safegen.ts
Labels: Review effort [1-5]: 2
